### ISSUE TITLE
Additional CDI camel context always created

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1177]
This is likely a bug. Even for deployments that are just @CamelAware there is a CamelContext created. It seems that CamelContext creation is too eager and triggers even if there are no Camel related CDI beans involved. 

https://issues.jboss.org/browse/ENTESB-5220

**Comment by astefanutti** [comment]
The Camel CDI extension has been updated to avoid creating an empty Camel context when no Camel primitives like route builders are present in the deployment, see [CAMEL-9904](https://issues.apache.org/jira/browse/CAMEL-9904).

So that issue will be fixed when WildFly Camel upgrade to the next Camel release.
