### ISSUE TITLE
Provide CI testing for camel-irc

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1327]
https://fabric8-ci.fusesource.com/view/wildfly-camel/job/wildfly-camel/lastCompletedBuild/testReport/org.wildfly.camel.test.irc/

**Comment by jamesnetherton** [comment]
I had a go at using freenode for this, it can work (eventually), but it exposed some flaws in the camel-irc component which make things tricky:

* There's no support for nick passwords on the producer
* There's no verification that the IRC user is fully initialised and registered before IRC messages are sent (so they just silently fail)

My preference would still be to use Docker to host a local IRC server, since it avoids the need to maintain separate accounts and rely on a 3rd party being available.

Either way, I'll raise upstream issues to address the camel-irc component problems.
