### ISSUE TITLE
Add support for component docker

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1424]

**Comment by jamesnetherton** [comment]
I looked at this recently in https://github.com/wildfly-extras/wildfly-camel/issues/1277.

Having to deal with all of the stuff that the [Docker Java Client](https://github.com/docker-java/docker-java) pulls in was somewhat painful. 

It'd be awesome to have a lightweight, minimal dependency Docker client library. Docker has started publishing a [Swagger YAML file](https://github.com/docker/docker/blob/master/api/swagger.yaml) which describes their API. So the potential exists to generate the API model and build a basic REST client around it, together with something that can talk to Linux sockets. Probably all a bit much for the scope of this task though...

**Comment by tdiesler** [comment]
In the context of this project, we should mainly deal with wildfly integration of whatever camel provides. However, if we have the resources, we can do this work in wfc first and then push it upstream to camel. I would generally recommend this as a recommended approach.

To avoid duplication of work, the camel folks should know about any such effort (i.e. through jira).

**Comment by jamesnetherton** [comment]
Perhaps another way of integrating this so that it plays nicely with WildFly would be to modify the Camel Docker component so that it can accept a custom `DockerCmdExecFactory`.

This would enable us to either:

* Configure the `NettyDockerCmdExecFactory` which could reuse the WildFly Netty modules.

Or

* We could create a custom `DockerCmdExecFactory` which leverages the WildFly RestEasy client to do the JAX-RS bits.

**Comment by jamesnetherton** [comment]
I'll take this one - I tweaked the component so that we can use Netty instead of Jersey as the JAX-RS client.

So I think we should limit our support to:

* Netty as the JAX-RS client
* Docker sockets exposed over TCP. I.e we don't support native unix sockets because this requires platform specific JARs containing native binaries

Needs Camel 2.19 so marking this as blocked till that's available.

**Comment by jamesnetherton** [comment]
For decent integration we need the docker-java client to be decoupled from Jersey (see this [docker-java](https://github.com/docker-java/docker-java/issues/513) issue).

Another possibility is the proposal that I've submitted to Camel where we cut Jersey out of the picture entirely and use Netty.

https://issues.apache.org/jira/browse/CAMEL-11256

**Comment by jamesnetherton** [comment]
I'll integrate this as-is and leave #2287 as something to revisit when we have an upgraded docker-java client in Camel.
