### ISSUE TITLE
Add support for component flink

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1430]
http://camel.apache.org/flink.html

**Comment by tdiesler** [comment]
Found 1 [matching posts](http://camel.465427.n5.nabble.com/template/NamlServlet.jtp?macro=search_page&node=465428&query=subject%3Aflink&days=700) for subject:flink in Camel - Users within 700 days

**Comment by jamesnetherton** [comment]
Integrating this is a bit of a nightmare due to Scala usage, copious use of shaded dependencies and the number of third party stuff that flink pulls in.

In any case, if we are going to integrate this, we should wait for Camel 2.20 as it uses Flink libraries aligned with Scala 2.11. 2.19.x depends on Scala 2.10, so we'd have to add our own Scala dependency and module slot for this.
