### ISSUE TITLE
Add support for component http

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1444]

**Comment by jamesnetherton** [comment]
This component uses HttpClient 3.x which is [EOL](http://hc.apache.org/). So maybe we should not include it and just continue with the camel-http4 component as it integrates nicely with the commons-http 4.x libraries that WildFly already provides.

Alternatively, maybe camel-http could be reworked and updated to use commons HTTP 4.x (so that we're left with just one camel-http component). Not sure if there are any plans to do that.

**Comment by tdiesler** [comment]
Ok, lets move it to rejected. This issue documents why.
