### ISSUE TITLE
Reject support for component jira

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1451]

**Comment by jamesnetherton** [comment]
I'm somewhat loathed to implement this. The Jira libraries are only available from the Atlassian Maven repository, meaning we'd need to maintain another maven `<repository>` in our POMs. This ended up being a pain for Restlet which is why we dropped support for it.

This component is not supported on Karaf so maybe we drop support for it as well.

**Comment by tdiesler** [comment]
ok, agreed
