### ISSUE TITLE
Provide camel-restlet support

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#159]

**Comment by jamesnetherton** [comment]
Some initial thoughts on trying to integrate this component

* It brings in a number of additional dependencies including spring-web (see below). It doesn't make sense to have all of these managed as individual modules so I've rolled them up into the camel component module definition. However, this makes the module def look quite verbose and somewhat unwieldy.

* There are two main ways to use this component:

1. By configuring an endpoint to listen on a specific hostname and port which leads to the component creating it's own HTTP server. This is working fine, although, this isn't something that we want to encourage as typically we want WildFly to manage and handle any such requests.

2. Configuring a `org.restlet.ext.spring.SpringServerServlet` in web.xml so that any requests are served by the underlying app server (which would be the ideal means of using this component). The problem with this is that it relies on spring-web and thus attempts to bootstrap the Camel context outside of the subsystem, resulting in the deployment failing with missing dependencies etc.

**Comment by tdiesler** [comment]
Initially, we should focus on REST endpoint creation through the already existing jaxrs subsystem. With that we need to find ways how to delegate incoming requests to a camel route. Incoming HTTP trafic on 8080 should all be handled by Undertow (also security).

Client requests should also go through what wildfly provides. Although I need to understand better how this is supposed to work.

Good camel rest integration would use a component (maybe this one) that provides integration hooks for both client & server side.

Generally, we should avoid creating alternative routes for non-trivial functionality that is already provided by wildfly (like providing an http server)

**Comment by tdiesler** [comment]
BTW, won't fix may be a valid resolution for this particular component. It means, we considered component integration, discussed benefits/draw backs and decided not to integrate it. It is then also document why we decided to not do it.

**Comment by jamesnetherton** [comment]
Ok, I'll investigate further. My feeling at the moment is that we don't incorporate this component. It's hard to see what benefit it provides over and above native WildFly JAX-RS support and the newer camel-rest functionality (which we are planning on including).

**Comment by jamesnetherton** [comment]
Wont fix (for now). 

Lengthy investigation of integrating Restlet leads to the conclusion of it being yet another JAX-RS endpoint with similar functionality already served by CXF, the Camel REST DSL and  easyrest WildFly JEE JAX-RS services. 

Given this, it's currently not worth investing in developing custom servlets etc, to support integration of this component.

**Comment by tdiesler** [comment]
Using restlet as producer only component (i.e. as jax-rs client) leads to 

```
15:56:21,610 SEVERE [org.jboss.arquillian.protocol.jmx.JMXTestRunner] (pool-1-thread-1) Failed: org.wildfly.camel.test.restlet.RestletProducerIntegrationTest.testRestletProducer: java.lang.NoClassDefFoundError: com/sun/net/httpserver/HttpHandler
	at org.restlet.engine.Engine.registerDefaultConnectors(Engine.java:845)
	at org.restlet.engine.Engine.discoverConnectors(Engine.java:662)
	at org.restlet.engine.Engine.<init>(Engine.java:495)
	at org.restlet.engine.Engine.register(Engine.java:386)
	at org.restlet.engine.Engine.register(Engine.java:372)
	at org.restlet.engine.Engine.getInstance(Engine.java:256)
	at org.restlet.Restlet.<init>(Restlet.java:131)
	at org.restlet.Restlet.<init>(Restlet.java:108)
	at org.restlet.Component.<init>(Component.java:181)
	at org.apache.camel.component.restlet.RestletComponent.<init>(RestletComponent.java:91)
```

**Comment by tdiesler** [comment]
restlet clients are now supported
