### ISSUE TITLE
CastorIntegrationTest fails on AIX

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1642]
https://issues.jboss.org/browse/ENTESB-6586

**Comment by jamesnetherton** [comment]
Likely this is caused by this https://github.com/castor-data-binding/castor/issues/50.

Castor has JDK specific XMLSerializerFactory impls that have to be activated via a setting in castor.properties. E.g:

`org.exolab.castor.xml.serializer.factory=org.exolab.castor.xml.AIXXercesJDK5XMLSerializerFactory `

Problem is that the loading of this properties file does not seem to work properly in a modular environment.
