### ISSUE TITLE
XmlSecurityIntegrationTest fails on AIX

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1652]
https://issues.jboss.org/browse/ENTESB-6596

**Comment by jamesnetherton** [comment]
I have a potential fix for this [here](https://github.com/jamesnetherton/wildfly-camel/commit/b3b26ffc1881aa3e1225699969145b2096424ff7) which enables this to work on IBM JDK by exporting the required path from the xalan module.

I don't fully understand the root cause of the issue though. There's some clash between the IBM JDK xalan stuff and the xalan library provided by WildFly.
