### ISSUE TITLE
Document usage of wildfly-camel on openshift.io

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1870]
[openshift.io](https://openshift.io) is in preview at the moment but lets get some documentation together on running our Docker image in this environment.

**Comment by ppalaga** [comment]
The pipeline used by OSIO does not have a notion of context-dir. Using a repo that contains all quickstarts as we have it now would thus not work.

I tried to split out the CDI quickstart and see if it could work. Some changes were necessary see https://github.com/ppalaga/wildfly-camel-example-camel-cdi The quickstart in its current form can be imported as exiting code to OSIO and the pipeline execution succeeds producing a working container. There is still this blocker https://github.com/openshiftio/openshift.io/issues/2980 The problem is that the image cannot be deployed for some reason.

I am turning to other tasks, because OSIO is slow and buggy ATM.
