### ISSUE TITLE
Improve Integration of CXF JAASAuthentication with WildFly security domains

### ISSUE THREAD

**Issue by jochenr** [wildfly-extras/wildfly-camel#1944]
Hi,

I'm not sure if I should ask for the feature "better JAASAuthentication integration with the JBossLoginModules" or if I should call my request "Support for client certificate login/TLS mutual authentication out of the box".

Please take a look at my example:
https://github.com/jochenr/wildfly-camel-examples/tree/20170914_backup_before_reset/camel-cxf-jaxws-security-cdi

In "org.wildfly.camel.examples.cxf.jaxws.JavaDSLRouteBuilder" I do a JAAS login with the JBoss  "org.jboss.security.auth.spi.BaseCertLoginModule" using the "JAASLoginInterceptor" from CXF.

They way I implemented it is not straightforward at all (I hope I dind't miss the obvious solution).
I found it espacially strange that I had to implement my own
	org.apache.cxf.interceptor.security.callback.CallbackHandlerProvider
	--> org.wildfly.camel.examples.cxf.jaxws.JBossCallbackHandlerTlsCert
to have the callbacks of the BaseCertLoginModule compatible with the callbacks used in CXF/camel-cxf.

So I have a general feature request to the wildfly-camel project to provide some convenience classes/methods to integrate with the wildfly security subbsystem and its JAAS login-modules for authentication and authorization.
In particular I have a use-case for client-certificate authentication with wildfly's certificate login modules.

Perhaps it is an idea to have a "WildflyJAASAuthenticationFeature" for CXF that is comparable with
https://github.com/apache/cxf/blob/master/core/src/main/java/org/apache/cxf/interceptor/security/JAASAuthenticationFeature.java
which focuses on Karaf....

Or perhaps a solution like
  org.jboss.wsf.stack.cxf.security.authentication.SubjectCreatingPolicyInterceptor
can be done for client-certificate/TLS mutual authentication.

I also found
https://issues.apache.org/jira/browse/CXF-5118
but I dond't think that it went into CXF.

Best regards,
Jochen

**Comment by jamesnetherton** [comment]
I fixed up the missing module bits for #1945 to make this work.

IMO the long term solution for this should be within CXF. I don't think we'd ideally want folks to add direct dependencies in their apps to our subsystem. This makes things a little tricky because of course CXF and WildFly / JBoss Webservices release under totally different timescales.

**Comment by jamesnetherton** [comment]
I fixed up the missing module bits for #1944 to make this work.

IMO the long term solution for this should be within CXF. I don't think we'd ideally want folks to add direct dependencies in their apps to our subsystem. This makes things a little tricky because of course CXF and WildFly / JBoss Webservices release under totally different timescales.

**Comment by jamesnetherton** [comment]
I think the Elytron integration work we did for camel-cxf more or less fulfils this requirement. See the 'secure' examples over at https://github.com/wildfly-extras/wildfly-camel-examples.
