### ISSUE TITLE
Add module authors guide to the documentation

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1965]
I don't think we clearly outline how one would go about adding a new Camel component module to the project.

It'd be useful for folks who are new to the project.

**Comment by jamesnetherton** [comment]
Rather than pollute the project docs, I ended up doing this as a series of blog articles:

http://jamesnetherton.github.io/2017/09/25/adding-a-new-component-to-the-wildfly-camel-subsystem-part1/

http://jamesnetherton.github.io/2017/09/25/adding-a-new-component-to-the-wildfly-camel-subsystem-part2/

**Comment by ppalaga** [comment]
Ad http://jamesnetherton.github.io/2017/09/25/adding-a-new-component-to-the-wildfly-camel-subsystem-part1/ :

* *Prerequisites: Maven installed* - I like when projects use Maven Wrapper a.k.a. `mvnw` because it makes the required version of Maven explicit.
* *Dependencies for org.apache.camel.apt and org.springframework.boot are skipped for all Camel component modules.* - perhaps add why: "... because they are not needed on WildFly".

Ad http://jamesnetherton.github.io/2017/09/25/adding-a-new-component-to-the-wildfly-camel-subsystem-part2/ :

* You forgot to note that the newly added component needs a piece of docs:
.
Add the new component to the docs in `docs/guide/components/index.adoc` and create a new documentation section for the component by creating e.g. `camel-geocoder.adoc`. You can use the other component docs as a reference for how we do things. We usually lazilly copy the opening sentence from the Apache Camel docs, https://github.com/apache/camel/blob/master/components/camel-geocoder/src/main/docs/geocoder-component.adoc.

**Comment by jamesnetherton** [comment]
Thanks for the feedback. I added some extra bits to my posts.

I'll raise an issue to get the Maven wrapper added. If WildFly has it, then I guess we should also.
