### ISSUE TITLE
Remove support for camel-couchbase

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2173]
A strange issue with Arquillian Cube not detecting that the Couchbase Docker container has started.

Tough to reproduce locally as it happens infrequently (for me at least).

CrossRef: https://issues.redhat.com/browse/ENTESB-12412

**Comment by tdiesler** [comment]
The current version of camel-couchbase does not support Couchbase Server 5.0 and beyond, which has already moved on to 6.0.
Test coverage has been disabled for over 2 years by now and I believe it is more sensible to remove support in Fuse EAP rather than claim that it is supported although it is not at a meaningful level.

**Comment by jamesnetherton** [comment]
It is planned to (eventually) update the Couchbase Client. See [CAMEL-14319](https://issues.apache.org/jira/browse/CAMEL-14319).
