### ISSUE TITLE
Stomp integration fails on EAP-7.1

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2271]

**Comment by ppalaga** [comment]
What are the steps to reproduce, @tdiesler ?

**Comment by tdiesler** [comment]
You uncomment this
https://github.com/jboss-fuse/wildfly-camel/blob/5.x-redhat/itests/standalone/extra/src/test/java/org/wildfly/camel/test/stomp/StompIntegrationTest.java#L59

**Comment by ppalaga** [comment]
This is caused by the fact that the `artemis-stomp-protocol` module is not available on EAP 7. There is more info in https://issues.jboss.org/browse/JBEAP-536 and https://access.redhat.com/solutions/2273801 This means that the `StompIntegrationTest` cannot use the broker embedded in EAP/WF to test against. It can start an Artemis instance itself like in `org.apache.camel.component.stomp.StompBaseTest`.
