### ISSUE TITLE
Spring archetype references BOM version for an undefined property

### ISSUE THREAD

**Issue by apupier** [wildfly-extras/wildfly-camel#2338]
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.wildfly.camel</groupId>
                <artifactId>wildfly-camel-bom</artifactId>
                <version>${version-wildfly-camel}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
version-wildfly-camel is not defined as a property.

**Comment by jamesnetherton** [comment]
Seems to be a problem with the Spring archetype specifically. The CDI one seems ok.

**Comment by jamesnetherton** [comment]
Not sure how the test suite is passing with it like this.

**Comment by apupier** [comment]
> Not sure how the test suite is passing with it like this.

Can it be that the property is defined at a Job level for instance? or global to the whole Maven reactor building the archetype?

**Comment by jamesnetherton** [comment]
Should be fixed now. Hope you don't mind, but I combined the other issues you spotted (typos etc) into this fix.

**Comment by apupier** [comment]
have you found why the test suite is not detecting the issue? I see nothing related to that in the commit.

> Hope you don't mind, but I combined the other issues you spotted (typos etc) into this fix.

no problem

**Comment by jamesnetherton** [comment]
It's because under test, [this property](https://github.com/wildfly-extras/wildfly-camel/blob/master/archetypes/archetype-spring/src/test/resources/projects/test-archetype-spring/archetype.properties#L10) was being plugged into the archetype generator.

It was broken when the archetype was generated manually because there was no default value set in `archetype-metadata.xml`.

**Comment by apupier** [comment]
> It's because under test, this property was being plugged into the archetype generator.

is it possible to avoid to have the property plugged into the archetype generator during test execution?

**Comment by jamesnetherton** [comment]
Not really because that's how the `archetype:integration-test` goal works. If you don't provide it with all of the expected properties, then it wont run.

It's maybe possible to look at alternatives to `archetype:integration-test`. Perhaps using the `maven-invoker` plugin to do the archetype generation and subsequent project build.
