### ISSUE TITLE
Introduce .editorconfig and enforce it with editorconfig-maven-plugin

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2395]
EditorConfig is an IDE-independent format for defining code formatting rules - see http://editorconfig.org/

## Objective

(1) Add a top level `.editorconfig` file, say 

```
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 4
trim_trailing_whitespace = true
end_of_line = lf
insert_final_newline = true

[module.xml]
indent_size = 2
```

I am open to discuss the the individual rules. E.g. we may want to omit `insert_final_newline = true` and we may want `indent_size = 2` for module.xml files. Thoughts?

(2) Add `editorconfig-maven-plugin` to the top pom to enforce the rules during the `verify` phase. See https://github.com/ec4j/editorconfig-maven-plugin#editorconfig-maven-plugin

(3) Fix the actual violations in a separate commit using `mvn editorconfig:format`

## Justification

Things like trailing whitespace, bad EOLs and improper indentation clutter the revision history. The `.editorconfig` format is supported by IntelliJ and many other editors OotB so the use should not bring much overhead.

Disclaimer: I am the author of `editorconfig-maven-plugin` and a co-author of the underlying `ec4j-core` library.

A PR follows.

**Comment by jamesnetherton** [comment]
I wanted to do this a while back (see https://github.com/wildfly-extras/wildfly-camel/issues/1314) but backed away from it given there were only 2 people contributing to the project full time. I'm all for introducing it though.

**Comment by ppalaga** [comment]
> I'm all for introducing it though.

Nice to hear that! 

Do you have an opinion about whether we want `insert_final_newline = true` and whether we should really have a special `indent_size = 2` for `module.xml` files? 

I have no preference about `insert_final_newline = true` and `indent_size = 2` for `module.xml` has the sole advantage that it makes the second commit smaller. 

I tend to like `indent_size = 2` for all `*.xml, *.xsl, ...` files, but here, it would change every line of every pom.xml file, which would be rather bad.

**Comment by tdiesler** [comment]
Yes, having that would be great.

**Comment by jamesnetherton** [comment]
There was a brief discussion about this:

```
<tdiesler> jnetherton, moin. some editor config stuff fails in -Pdocker https://fabric8-ci.fusesource.com/view/wildfly-camel/job/wildfly-camel-docker/846/console
<jnetherton> tdiesler: yeah I was discussing with Peter last night
<jnetherton> tdiesler: Here's the PR of a proposed fix https://github.com/wildfly-extras/wildfly-camel/pull/2402
<tdiesler> jnetherton, yes, this is quite a hack
<jnetherton> we either need to implement a fix now - or back it out... the default mvn workflow is currently broken
<tdiesler> jnetherton, back out, I'd say
<jnetherton> tdiesler: ok
```
I think the implementation of this needs a rethink. Since our current iteration end is fast approaching, I'll remove the plugin configuration from the project for now. The `.editorconfig` file can remain as it's still useful, even without the plugin.

Either the plugin needs to some how work better with our profile setup, or we need to find a less invasive way of integrating it into our project workflow.

We don't have to run the plugin at the verify phase by default. We could activate the plugin via a profile as and when required.

Something I've been thinking about for some time is adding additional checks to the PR process. E.g license header checks, code linting etc. We could set up dedicated build jobs to fire on each PR, but only activate the relevant plugin lifecycles.
