### ISSUE TITLE
Review dependency on Spring JtaTransactionManager

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#267]
The TransactedJMSIntegrationTest has a dependency on Spring JtaTransactionManager. Transactional JMS should probably work without Spring.

**Comment by jamesnetherton** [comment]
Reopening.... 

I think this needs revisiting. Turns out there are two issues here.....

1. Our transacted JMS integration test doesn't actually use any Camel transactional capability. E.g there's no .transacted() step within any of the routes (my fault).

2. camel-jms is tightly coupled to Spring and is built around spring-jms. The component requires a transaction manager of type PlatformTransactionManager. Which means we can't just look up 'java:/TransactionManager' from JNDI and configure it on the JMS component.

From all the documentation and examples that I've seen for using camel-jms in JEE containers,  the transaction manager is typically a JtaTransactionManager (obviously it depends on the use case).
