### ISSUE TITLE
Revisit license processing during normal build

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2796]
Every now and than and more frequently than I like some license build failure blocks all further progress.

Like ...

```
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:1.20.jbossorg-2:licenses-xml-insert-versions (licenses-xml-insert-versions) 
on project wildfly-camel-feature-modules: Could not resolve version of com.intellij:annotations 
in file /Users/tdiesler/git/wildfly-camel/feature/modules/target/licenses/licenses.xml
```

Also, I don't think that these license [html files](https://github.com/wildfly-extras/wildfly-camel/tree/master/feature/modules/src/main/license-resources/licenses) need to be tracked in source control. Instead, it should be sufficient to build/include them in every tagged revision i.e. to have this done as one of the documented steps in the [release procedure](https://github.com/wildfly-extras/wildfly-camel/wiki/Release-Procedure#release-the-binaries)

**Comment by ppalaga** [comment]
Is this happening after https://github.com/wildfly-extras/wildfly-camel/pull/2795 ?

**Comment by tdiesler** [comment]
It's happening with camel-3.0 on wfc master. Please remove all license stuff from the normal build - it can happen in a profile that we activate during release.

**Comment by ppalaga** [comment]
The current approach tries to be incremental, i.e. only changes in the FP dependency set should require the full rebuild of license.xml file (which tends to be costy). 

I find it better to both discover and solve the changes as they come rather than solve them all at once on release.

If you strongly prefer the per release approach, please feel free to implement it.

**Comment by tdiesler** [comment]
James and I, think that the ad-hoc approach is the way to go and I'm asking you to fix it.

**Comment by ppalaga** [comment]
I am in favor of keeping the current state, I am not going to change it and at the same time I am not going to veto anybody else to implement the per release approach.

The per release approach would be hard to keep in sync with the product where we aim at continuous productization.

**Comment by tdiesler** [comment]
We can do this is a branch and over time as it more matures and Peter still thinks that it is worth bringing into master, we revisit. As we do this stuff, we'll likely get a better idea of whether/why it ought to move upstream. For now, we keep it simple and maintain the version in prod, which is the one that is needed.

**Comment by ppalaga** [comment]
Here are the reasons why I think we should keep the incremental approach:

Producing licenses.xml is still quite a new area for which we have not found a reliable and satisfactory solution. Disabling it in the default build would prevent us from seeing issues as soon as they appear. I expect the most issues to happen due to changes in the dependency hierarchy. Resolving such issues should be a common knowledge in our team, similar to resolving other dependency related issues which we do on daily basis, mainly when upgrading Camel and WildFly. We all do prefer fixing those incrementally in smaller chunks and that's exactly why we do weekly rebases. Leaving Camel and WildFly upgrades for the time shortly before the release would make it harder and longer to solve the issues due to higher complexity. It is the same with producing licenses.xml.

Second, because the area is quite new, there may also exist issues in the tooling. It is very risky to discover them shortly before release when there is no time to fix them. I am ready to assist with these.

I am vetoing the complete removal of licenses.xml generation from the build. We will need the current setup for the next major version of the product.

I am proposing to take the strategy of temporarily disabling parts that block team members from doing other stuff and creating issues assigned to me.

A separate branch means too much overhead.
