### ISSUE TITLE
WSPasswordCallback no longer on classpath

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2818]
Happens on the wildfly-17.x branch

```
import org.apache.wss4j.common.ext.WSPasswordCallback
```

**Comment by ppalaga** [comment]
The `ClientCallbackHandler` is actually not needed at all. It is probably just a left over from some initial copy&paste. The whole `ClientCallbackHandler` class can be removed. When the easy compile errors are fixed, the test is still failing. It does not look like a fault of WF because when I ported the test to WF master, it passed there. Comparing the flow on WFC@WF17 with WFC master shows that the interceptors defined in https://github.com/wildfly-extras/wildfly-camel/blob/44ec94d294adec585b32f19a683f2f7ee69f28b5/itests/standalone/basic/src/test/java/org/wildfly/camel/test/cxf/ws/subA/UsernameTokenEndpointImpl.java#L43-L46 are not called for some reason. I will investigate further on Monday.

**Comment by tdiesler** [comment]
merci
