### ISSUE TITLE
Limited wildfly-camel distribution pack

### ISSUE THREAD

**Issue by jarek-przygodzki** [wildfly-extras/wildfly-camel#2925]
Is there a way to build a wildfly-camel distribution with only selected components?

**Comment by jamesnetherton** [comment]
The stuff that generates the module definitions and feature pack lives in `etc/smartics` under subdirectories of the `feature` module. You could remove or comment out the modules that are not required.

Otherwise, the lazy way would be to add some additional excludes to the [patch distribution assembly](https://github.com/wildfly-extras/wildfly-camel/blob/master/patch/scripts/assembly-wildfly-patch.xml).  

Obviously you need to be a bit careful when doing this so as not to remove modules that others may depend on.

**Comment by jarek-przygodzki** [comment]
Just removing unwanted  modules from _feature/modules/etc/smartics/camel-modules.xml_  (only components, names like org.apache.camel.component.*) does not work: build fails with

```
[ERROR] Failed to execute goal org.wildfly.galleon-plugins:wildfly-galleon-maven-plugin:4.0.4.Final:build-feature-pack (feature-pack-build) on project wildfly-camel-feature-modules: Package org.apache.camel.camel-beanio has unsatisifed external dependency on package org.apache.camel.apt
```
_org.apache.camel.apt_ is certainly not among the removed modules Any ideas how to fix this?

**Comment by jamesnetherton** [comment]
Sorry, I forgot you also need to remove the Maven dependency for the component from `feature/modules/pom.xml`.

**Comment by tdiesler** [comment]
Here is a [commit](https://github.com/wildfly-extras/wildfly-camel/commit/6f4a30eb466b0e8e7a0ae7952298f35e9b981693) that removes camel-linkedin.
