### ISSUE TITLE
Migrate away from arquillian-cube

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2986]
This project seems dead with the last release 1.18.2 in Oct-2018
https://github.com/arquillian/arquillian-cube/tree/1.18.2

**Comment by tdiesler** [comment]
Perhaps we should go with https://github.com/docker-java/docker-java

**Comment by jamesnetherton** [comment]
Or https://www.testcontainers.org/. Which, like arq-cube, is a wrapper around docker-java.

**Comment by tdiesler** [comment]
Here my [POC](https://github.com/tdiesler/wildfly-camel/blob/ghi2986/itests/standalone/dockerjava/src/test/java/org/wildfly/camel/test/consul/ConsulIntegrationTest.java#L85) with docker-java. It uses a simple docker cmd API from a SetupTask. Would that work for you?

**Comment by jamesnetherton** [comment]
Yes that seems simple enough 👍

**Comment by bsideup** [comment]
As a maintainer of both Testcontainers and `docker-java`, I strongly recommend going with Testcontainers if your use case is testing.

Just a few examples based on the PoC shared:
- it will not work on Windows (because it uses `DockerClientBuilder.createDefaultClientBuilder().build()` and does not know about npipe)
- if JVM is terminated (e.g. with `kill -9`) while running the test, the container will not get removed
- Testcontainers uses random ports and gives tooling to obtain actual values, while the PoC is using fixed ports
- [`TestUtils.getDockerHost()`](https://github.com/tdiesler/wildfly-camel/blob/84b4aac0a6765d8209f338979a186e1774ed9e2f/itests/common/src/main/java/org/wildfly/camel/test/common/utils/TestUtils.java#L33) is too naive :) Just compare it to [Testcontainers' analogue](https://github.com/testcontainers/testcontainers-java/blob/6a005390d670632d63cef2c6bf8939cf76725341/core/src/main/java/org/testcontainers/dockerclient/DockerClientProviderStrategy.java#L230)

Testcontainers isn't just a wrapper around `docker-java`, but more than 5 years of experience of testing with Docker :)

**Comment by tdiesler** [comment]
Our use case is to run a series of test for the camel/wildfly integration. The test cases run on the appserver using the Arquillian framework (i.e. these are not simple client side junit tests). Some of the camel components that we test make connections to 3rd party services that we somehow need to provide externally - for these 3rd party services we use docker containers. The lifecycle of which must be controlled by Arquillian, for which we use ServerSetupTasks. This is similar to @BeforeClass/@AfterClass but runs on the client side and not as part of the normal test case lifecycle, which runs on the appserver. As the name suggests, these ServerSetupTasks are primarily used to bring the appserver in a certain state suitable for the test that is about to run (e.g. tweak the config, install jca stuff, create jms queues/topics, etc)

Using fixed ports is totally fine for now, as well as no support for npipe. This naive impl of getDockerHost (i.e. localhost by default, an override with a known IP if needed) is also fine for now - in fact hardcoded 'localhost' would do AFAIK.

Ideally, I would like to have some declarative means like [this|https://github.com/wildfly-extras/wildfly-camel/blob/11.1.0/itests/standalone/docker/src/test/resources/arquillian.xml#L39] which is then used by a thing that hooks into Arquillian lifecycle callbacks. In the end it needs to be able to start/stop docker containers on before/after class without affecting the client side classpath nor what is run on the appserver.

**Comment by tdiesler** [comment]
Well, then please go ahead and show me how. PRs that improve stuff are always welcome. You may want to wait until this shows up on master, but I'm of cause also happy to work with you on [this WIP branch](https://github.com/tdiesler/wildfly-camel/tree/ghi2986)

**Comment by bsideup** [comment]
@tdiesler well, I consider advising you on the library usage is a big enough contribution on its own.
We're trying to ensure that Testcontainers' has a good enough documentation that is easy to follow and start with, there is a plenty of examples as well.
Last but not least, you will find enough colleagues & projects at Red Hat that know and use Testcontainers for quite some time and can help you.

Good luck.

**Comment by tdiesler** [comment]
Now that this is done, we could now see whether and how testcontainers can bring benefit to the table. The current approach uses code [like this](https://github.com/wildfly-extras/wildfly-camel/blob/master/itests/standalone/docker/src/test/java/org/wildfly/camel/test/consul/ConsulIntegrationTest.java#L82) from ARQ setup tasks ...

```
/*
docker run \
	--name consul \
	-p 48802:48802 \
	consul:0.9.3 agent -dev -server -bootstrap -client 0.0.0.0 -http-port 48802 -log-level trace
*/

dockerManager = new DockerManager()
		.createContainer("consul:0.9.3", true)
		.withName(CONTAINER_NAME)
		.withPortBindings(CONSUL_PORT + ":" + CONSUL_PORT)
		.withCmd("agent -dev -server -bootstrap -client 0.0.0.0 -http-port " + CONSUL_PORT + " -log-level trace")
		.startContainer();

dockerManager
	.withAwaitLogMessage("agent: Synced node info")
	.awaitCompletion(60, TimeUnit.SECONDS);
```
