### ISSUE TITLE
How to apply the patch to existing wildfly instance

### ISSUE THREAD

**Issue by francesco-clementi-92** [wildfly-extras/wildfly-camel#3051]
Is there a guide to apply this patch to an existing wildfly instance?

Can't find a way to do it.

**Comment by pSub** [comment]
I am having the same trouble. I do not see a way to install wildfly-camel into an existing wildfly instance.

The README tells us to 

> Simply apply the wildfly-camel-patch to a compatible wildfly version.

However, the archives (zip as well as tar.gz) do **not** look like valid wildfly patches. Consequently applying the patch via CLI `patch apply` or via the management console fails. I tried to create a wildfly patch following a [tutorial](https://in.relation.to/2017/05/29/creating-patches-for-wildfly/) using [patch-gen](https://github.com/jbossas/patch-gen). patch-gen aborted with this error message
```
java.lang.RuntimeException: invalid layer configuration for fuse
	at org.jboss.as.patching.generator.PatchGenerator.processingError(PatchGenerator.java:355)
	at org.jboss.as.patching.generator.PatchBuilderWrapper.addLayer(PatchBuilderWrapper.java:96)
	at org.jboss.as.patching.generator.PatchBuilderWrapper.compare(PatchBuilderWrapper.java:188)
	at org.jboss.as.patching.generator.PatchBuilderWrapper.compare(PatchBuilderWrapper.java:85)
	at org.jboss.as.patching.generator.PatchGenerator.process(PatchGenerator.java:172)
	at org.jboss.as.patching.generator.PatchGenerator.main(PatchGenerator.java:73)
```

Maybe there is something wrong with my very simple patch-gen config. However I am by no means an expert for wildfly patches.

After poking around in the sources of wildfly-camel I stumbled across Galleon feature packs for wildfly-camel. Again I am not sure which feature pack (from https://github.com/wildfly-extras/wildfly-camel/tree/master/feature) is the correct one. My first try was `wildfly-camel-feature-pack` which resulted in 

```
$ ./galleon.sh install --dir=~/sandbox/wildfly  org.wildfly.camel:wildfly-camel-feature-pack:12.0.0
Resolving feature-pack wildfly-camel-feature-modules:current#12.0.0Error: Install failed.
 * Producer wildfly-camel-feature-modules is not found in the universe
```

therefore I tried `wildfly-camel-feature-modules`, which looked very promising … to a certain point. It downloaded a bunch of stuff from Maven central and stopped with

```
$ ./galleon.sh install --dir=~/sandbox/wildfly org.wildfly.camel:wildfly-camel-feature-modules:12.0.0
Feature-packs resolved. 
Packages installed. 
Installing JBoss modules 694 of 915 (75.8%)Error: Install failed.
 * Failed to process JBoss module XML template for feature-pack wildfly-camel-feature-modules@maven(org.jboss.universe:community-universe):current#12.0.0 package com.github.ipfs
  * Failed to resolve artifact com.github.ipld:java-cid:jar:v1.1.0
   * Failed to resolve com.github.ipld:java-cid:jar:v1.1.0
    * Could not find artifact com.github.ipld:java-cid:jar:v1.1.0 in maven-central (https://repo1.maven.org/maven2/)
     * Could not find artifact com.github.ipld:java-cid:jar:v1.1.0 in maven-central (https://repo1.maven.org/maven2/)
```
Not sure how this could have ever worked since there is no artifact for the group `com.github.ipld` and in the readme of `java-cid` (https://github.com/ipld/java-cid) only the Jitpack repository is mentioned. Maybe they moved away from Maven central. I put a version of this jar in my local Maven repository but could not convince the Galleon to use it. Maybe this is easier with the Galleon Maven plugin, but I haven't tried it yet. Even if this would work, it would be very ugly.

The only way I was able to use wildfly-camel in an exisiting wildfly instance was by copying everything that is in the release archive into my existing wildfly. From what I could see, this works without any problems. However I only tested this with a small PoC and copied the files in an otherwise untouched wildfly instance. However, I have the feeling that this approach could backfire pretty quickly (eg. by overwriting some files).

This (blind) copying is described in the [user guide](https://github.com/wildfly-extras/wildfly-camel/blob/master/docs/guide/start/index.adoc#installing-the-camel-subsystem) as the way to install wildfly-camel into an exisiting wildfly instance:

> Simply unpack the provided patch into the a supported WildFly installation. For possible WildFly target versions, see the compatibility page.

I would love to hear that there is an easy way to install wildfly-camel into an exisiting wildfly instance. Just copying the files over does not seem to be the right solution and I do not want to provision our production servers using it.

**Comment by pSub** [comment]
Why did you close this issue, @tdiesler? As far as I can see there are still no instructions on how to apply the patch to an existing Wildfly instance.

**Comment by tdiesler** [comment]
See: https://github.com/wildfly-extras/wildfly-camel/issues/3053
