### ISSUE TITLE
Global dependency exclude for org.osgi.core needed

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#522]
We explicitly exclude org.osgi.core in the smartics config, as well as in wildfly-modules.xml

**Comment by jamesnetherton** [comment]
What do we mean by 'explicit exclude'?

Either we exclude dependencies completely by using the smartics dependencyExcludes property or we skip them in the module configuration files.

The alternative is to use Maven excludes against specific dependencies. This does not seem to be a viable option IMO given that most of our dependencies are now up in the Camel BOM. Redeclaring them to do exclusions sounds messy to me.

If we want consistency, then the simplest thing to do IMO is to remove the smartics dependencyExcludes config section and allow the smartics module skipping to do its thing.

**Comment by jamesnetherton** [comment]
Thinking about this some more, I see two scenarios.

1. We want to totally exclude a specific dependency (for example org.linkedin).

2. We want to include a dependency but we do not want smartics to create a module definition for it since WildFly already provides it (for example osgi.core).

In scenario 1 this is best served with the smartics dependencyExcludes config. For scenario 2, we can declare the module / dependency as skipped.

Therefore, the consolidation work done in #460 probably needs revisiting to achieve the correct balance between absolute dependency exclusion and module skipping.

**Comment by tdiesler** [comment]
We do generally not want to globally exclude stuff via dependencyExcludes because it also removes the need to exclude those dependencies explicitly per module. For documentation purposes it is useful to have 

```
        <apply-to-dependencies skip="true">
            <include module="org.osgi.compendium" />
            <include module="org.osgi.core" />
        </apply-to-dependencies>
``` 

Like explicit includes, we also like to be explicit about excludes on a per module basis. If we should ever run into a CNF situation we can look at our smartics module definition (and nowhere else) and reason about the generated modules def.

Currently, we cannot get rid of global dependencyExcludes because of a smartics bug which deteriorates performance to an unacceptable degree.

An initial patch for this issue is in [branch/wfc522](https://github.com/tdiesler/wildfly-camel/tree/wfc522) - I suspect this also requires a smartics update.
