### ISSUE TITLE
Investigate usage of maven-changes-plugin

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#524]
This should give a good head start for the changelog

**Comment by jamesnetherton** [comment]
At a first glance, this plugin is very Jira centric (with some basic GitHub support) and only seems capable of generating Maven site style documentation. 

If the goal of this issue is to generate the change log, I can do this with a simple Groovy script (or TCL if you prefer :wink:) to produce the docs/Changelog.md file.

**Comment by tdiesler** [comment]
yeah, anything that saves me from doing these manual copy/paste actions for dozens of issues would help
