### ISSUE TITLE
Verify that Hawtio camel tab works as expected 

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#555]
As part of the resolution we would like to have a basic markdown protocol in the project repo similar to what we have already in the docs folder. Going trough those hwatio items can then become part of the release procedure and ultimately be automated in some hawtio console tests that run in jenkins.

**Comment by jamesnetherton** [comment]
I ran into a scenario where route diagrams do not work. 

To reproduce the problem, make sure there are no Camel Spring XML contexts configured in the [standalone.xml config file](https://github.com/wildfly-extras/wildfly-camel/blob/master/itests/distro/etc/wildfly/standalone/configuration/standalone-camel-examples.xml#L166-L175) . Then run & deploy the [camel-cdi example](https://github.com/wildfly-extras/wildfly-camel/tree/master/examples/camel-cdi).

Launch hawtio, browse to the cdi-camel-context and try to view the route diagram. It will fail.

I believe this problem is documented here: https://github.com/hawtio/hawtio/issues/1915. And [here](https://developer.jboss.org/thread/249136). [This method](https://github.com/apache/camel/blob/master/camel-core/src/main/java/org/apache/camel/model/ModelHelper.java#L48-L62) seems to be the entry point to the issue.

Strangely, this issue does not occur with camel spring XML contexts or if a spring xml context has already been deployed.

**Comment by grgrzybek** [comment]
Thanks @jamesnetherton for describing the issue - I'll check it

**Comment by grgrzybek** [comment]
Trying now.
No error in logs, but I can see this, when hawtio fails to display source:
```
2015-05-08 11:35:38,141 FINE  [javax.xml.bind] (default task-9) Searching jaxb.properties
2015-05-08 11:35:38,141 FINE  [javax.xml.bind] (default task-9) Searching the system property
2015-05-08 11:35:38,141 FINE  [javax.xml.bind] (default task-9) Searching META-INF/services
2015-05-08 11:35:38,142 FINE  [javax.xml.bind] (default task-9) Reading jar:file:/home/ggrzybek/sources/github.com/jboss-fuse/wildfly-camel/examples/distro/target/wildfly-8.2.0.Final/modules/system/layers/base/com/sun/xml/bind/main/jaxb-impl-2.2.5.jboss-2.jar!/META-INF/services/javax.xml.bind.JAXBContext
2015-05-08 11:35:38,142 FINE  [javax.xml.bind] (default task-9) Trying to load com.sun.xml.bind.v2.ContextFactory
2015-05-08 11:35:38,144 FINE  [com.sun.xml.bind.v2.ContextFactory] (default task-9) Property com.sun.xml.bind.XmlAccessorFactoryis not active.  Using JAXB's implementation
```
JAXB 2.2.5? Shouldn't we use 2.2.11?

**Comment by grgrzybek** [comment]
I checked https://github.com/hawtio/hawtio/issues/1915, but there, WAR contained JAXB 2.2.11 impl+core.

**Comment by jamesnetherton** [comment]
Another problem....

Select a Camel Route from the tree view and then choose the 'Source' tab. Now try to edit the route XML and click 'Update'. I cannot get this to work. The error from hawtio is:
```
[Core] Operation unknown failed due to: javax.management.RuntimeErrorException : Error occurred in RequiredModelMBean while trying to invoke operation addOrUpdateRoutesFromXml
```
And in the WildFly server.log
```
DEBUG [org.apache.camel.impl.DefaultLanguageResolver] (default task-33) Ignored error looking up bean: . Error: org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException: name must be specified and not empty
```

**Comment by tdiesler** [comment]
Please don't forget, release date for this is Monday 01-Jun

**Comment by grgrzybek** [comment]
Sure, I remember ;)

2015-05-28 8:55 GMT+02:00 Thomas Diesler <notifications@github.com>:

**Comment by grgrzybek** [comment]
Draft *instruction*:


After wildfly-camel is built, let's run the server inside `itests/standalone/target/wildfly-8.2.0.Final`

Let's add `admin/admin` Management User without any special roles:

    cd itests/standalone/target/wildfly-8.2.0.Final
    14:42 $ bin/add-user.sh 
    
    What type of user do you wish to add? 
     a) Management User (mgmt-users.properties) 
     b) Application User (application-users.properties)
    (a): a
    
    Enter the details of the new user to add.
    Using realm 'ManagementRealm' as discovered from the existing property files.
    Username : admin
    The username 'admin' is easy to guess
    Are you sure you want to add user 'admin' yes/no? y 
    Password recommendations are listed below. To modify these restrictions edit the add-user.properties configuration file.
     - The password should not be one of the following restricted values {root, admin, administrator}
     - The password should contain at least 8 characters, 1 alphabetic character(s), 1 digit(s), 1 non-alphanumeric symbol(s)
     - The password should be different from the username
    Password : 
    JBAS152565: Password must not be equal to 'admin', this value is restricted.
    Are you sure you want to use the password entered yes/no? y
    Re-enter Password : 
    What groups do you want this user to belong to? (Please enter a comma separated list, or leave blank for none)[  ]: 
    About to add user 'admin' for realm 'ManagementRealm'
    Is this correct yes/no? y
    Added user 'admin' to file '/data/ggrzybek/sources/github.com/jboss-fuse/wildfly-camel/itests/standalone/target/wildfly-8.2.0.Final/standalone/configuration/mgmt-users.properties'
    Added user 'admin' to file '/data/ggrzybek/sources/github.com/jboss-fuse/wildfly-camel/itests/standalone/target/wildfly-8.2.0.Final/domain/configuration/mgmt-users.properties'
    Added user 'admin' with groups  to file '/data/ggrzybek/sources/github.com/jboss-fuse/wildfly-camel/itests/standalone/target/wildfly-8.2.0.Final/standalone/configuration/mgmt-groups.properties'
    Added user 'admin' with groups  to file '/data/ggrzybek/sources/github.com/jboss-fuse/wildfly-camel/itests/standalone/target/wildfly-8.2.0.Final/domain/configuration/mgmt-groups.properties'
    Is this new user going to be used for one AS process to connect to another AS process? 
    e.g. for a slave host controller connecting to the master or for a Remoting connection for server to server EJB calls.
    yes/no? n

Let's check if there's hawtio role configured (in `standalone-camel.xml`)

    <system-properties>
      <property name="hawtio.authenticationEnabled" value="true"/>
      <property name="hawtio.offline" value="true"/>
      <property name="hawtio.realm" value="hawtio-domain"/>
      <property name="hawtio.role" value="admin"/>
    </system-properties>

If there's `hawtio.role=admin`, please remove it. Otherwise the user created earlier won't be able to log in (having no special roles configured)

Let's start WF:

    bin/standalone.sh -c standalone-camel.xml

Without any changes, this will start WF-Camel without default route deployed, there's:

    <subsystem xmlns="urn:jboss:domain:camel:1.0">
      
      
    </subsystem>

(example camel context is commented out)

We should be able to see this in console:

    15:21:06,337 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) JBAS015876: Starting deployment of "hawtio-wildfly-1.4.50.war" (runtime-name: "hawtio-wildfly-1.4.50.war")
    ...
    15:21:08,450 INFO  [io.hawt.jmx.JmxTreeWatcher] (MSC service thread 1-7) Welcome to hawtio 1.4.50 : http://hawt.io/ : Don't cha wish your console was hawt like me? ;-)
    15:21:08,453 INFO  [io.hawt.jmx.UploadManager] (MSC service thread 1-7) Using file upload directory: /tmp/uploads
    ...
    15:21:10,606 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) JBAS017534: Registered web context: /hawtio
    15:21:10,670 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 29) JBAS018559: Deployed "hawtio-wildfly-1.4.50.war" (runtime-name : "hawtio-wildfly-1.4.50.war")

Browse to http://localhost:8080/hawtio, login screen will be opened. We will see this in the logs:

    15:23:32,162 INFO  [io.hawt.web.AuthenticationFilter] (default task-1) Starting hawtio authentication filter, JAAS realm: "hawtio-domain" authorized role(s): "*" role principal classes: "org.jboss.security.SimplePrincipal"

Which means hawtio JAAS authentication was successfully integrated with WF security. We should be able to log in using
`admin` user with the password specified for `addUser.sh` script.

Hawtio should not present any "Camel" tabs, as we have no camel context deployed. There should be:

* Connect
* Dashoard
* JBoss
* JMX
* Threads

tabs. Under JBoss→Applications tab we can see `hawtio-wildfly-1.4.x.war` application deployed under `/hawtio` context.

Let's deploy some camel contexts. Drop:

* `wildfly-camel/itests/standalone/src/main/resources/spring/transform1-camel-context.xml `
* `wildfly-camel/itests/standalone/src/main/resources/spring/transform2-camel-context.xml `

into `wildfly-camel/itests/standalone/target/wildfly-8.2.0.Final/standalone/deployments ` without restarting anything.
We should see new "Camel" tab in hawtio.

This tab presents subset of JMX tree - objects in `org.apache.camel` domain.

1. From the *Camel Contexts* selection we can start/pause/destroy contexts
2. From *transform1* node we can see JMX properties and operations of context. *Charts* show changes of attribute values over time
3. When you click *transform1/Routes* or *transform1/Routes/route1*, we should see source view of camel route(s), we can modify it and update.
   This should be visible in logs (route restart):

        17:16:35,977 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (default task-22) Starting to graceful shutdown 1 routes (timeout 300 seconds)
        17:16:35,984 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (Camel (transform1) thread #0 - ShutdownTask) Route: route1 shutdown complete, was consuming from: Endpoint[direct://start]
        17:16:35,985 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (default task-22) Graceful shutdown of 1 routes completed in 0 seconds
        17:16:35,986 INFO  [org.apache.camel.spring.SpringCamelContext] (default task-22) Route: route1 is stopped, was consuming from: Endpoint[direct://start]
        17:16:35,987 INFO  [org.apache.camel.spring.SpringCamelContext] (default task-22) Route: route1 is shutdown and removed, was consuming from: Endpoint[direct://start]
        17:16:36,012 INFO  [org.apache.camel.spring.SpringCamelContext] (default task-22) Route: route1 started and consuming from: Endpoint[direct://start]

4. e.g., I changed `<simple>Hello ${body}</simple>` to `<simple>Hello ${body} 2</simple>`, this change was reflected on both
   the diagram and a list of properties of *transform* EIP block

Now we can try restarting WF after uncommenting default camel context inside `<subsystem xmlns="urn:jboss:domain:camel:1.0">`
in `wildfly-camel/itests/standalone/target/wildfly-8.2.0.Final/standalone/configuration/standalone-camel.xml`.

**Comment by tdiesler** [comment]
Deferred

**Comment by grgrzybek** [comment]
@tdiesler do you need more from me? I'd like to forward the above instruction to people dealing with qa.

**Comment by tdiesler** [comment]
The requirements to resolve this have not changed. "As part of the resolution we would like to have a basic markdown protocol in the project repo similar to what we have already in the docs folder."

**Comment by grgrzybek** [comment]
https://github.com/wildfly-extras/wildfly-camel/pull/830

**Comment by grgrzybek** [comment]
docs/Hawtio.md available [here](https://github.com/wildfly-extras/wildfly-camel/blob/9dc2dabada178c69a051bb9243c387adf08560ff/docs/Hawtio.md).
