### ISSUE TITLE
Add support for camel-elasticsearch

### ISSUE THREAD

**Issue by EgonPedersen** [wildfly-extras/wildfly-camel#814]
http://camel.apache.org/elasticsearch.html

**Comment by jamesnetherton** [comment]
Good idea, I'll take a look into this.

**Comment by jamesnetherton** [comment]
ES 1.4.4 will only work with Lucene 4.10.3 and WildFly provides 4.10.4. I don't want to introduce another Lucene module without good reason.

Therefore, this is blocked pending a Camel Lucene & Elasticsearch component upgrade.

**Comment by jamesnetherton** [comment]
Cross ref: https://issues.apache.org/jira/browse/CAMEL-9080

**Comment by tdiesler** [comment]
Blocked on camel-2.16 and higher wildfly

**Comment by jamesnetherton** [comment]
Wondering whether adding this component is a good idea. ES does checks against the Lucene version and wont work unless the correct version is available.

This effectively ties WFC to specific Lucene releases. Ideally we always want to reuse the Lucene modules provided by the application server. This may, or may not be possible, depending on the versions WildFly has decided to use.

Otherwise we're potentially going to have to add and maintain custom Lucene modules just to support ES.

**Comment by tdiesler** [comment]
I'd say because Lucene is not a core JavaEE functionality of the appserver, we are free to install an alternative version, which we have done in the past already. This would be the Lucene version that comes with Camel and would already be supported in the Karaf based runtime.

Both teams (wildfly + camel) have an interest that stuff works well together. I feel that aligning the Lucene versions should not be a problem because of this. If it is (because of some technical necessity) we can temporarily fallback to the above.

**Comment by jamesnetherton** [comment]
Seems that the Camel 2.16 RC is going to be recut shortly, so we should be able to get this into the 3.1.0 release.
