### ISSUE TITLE
Cannot use maven release plugin 

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#905]
With the 3.1.0 release we had various issues using the release:prepare + release:perform combination.
Artefacts did not get installed in the local mvn repo. Profiles did not get activated by the release target.

Please verify that what we [document in the wiki](https://github.com/wildfly-extras/wildfly-camel/wiki/Release-Procedure#release-the-binaries) actually works.

If these issues are caused by recent mvn versions, please find the last version that works and report these issues in the mvn jira.

**Comment by jamesnetherton** [comment]
I think this comes down to a misunderstanding of how the release plugin works and consequently a misconfiguration of it. The release process has probably never worked as intended.

The release:prepare lifecycle looks something like this:

* Build project
* Change maven POM SNAPSHOT versions to desired release version
* Rebuild to verify that the changes are ok before tag & commit to SCM

By default, the rebuild step does not propagate any arguments passed to the build (E.g -Dts.all). Also, the default phases are set to 'clean verify', which means 'install' never runs.

We can add the following to the release plugin config to fix this:

    <arguments>-Dts.all -Ddocker</arguments>
    <preparationGoals>clean install</preparationGoals>

And as a 'nice to have':

    <tagNameFormat>@{project.version}</tagNameFormat>

The release documentation should also include the 'clean' phase for release:prepare / perform since there may be old stuff lingering around in target directories.

If we can resolve #933 then everything's set for the release procedure to work on any Maven version.

**Comment by jamesnetherton** [comment]
In addition, it really is time we automated this stuff. We should be releasing from a consistent environment with known Java, Maven, Git & Docker versions (E.g from Jenkins).

Otherwise we risk a world of pain trying to release on different platforms, versions etc.
